#### **Задание 7. Вариант 3**

**Задача 1** \
Даны матрица A[4][4] вещественных чисел и константа К. Вычислить матрицу С = А*К.

In [10]:
import numpy as np

In [11]:
A = np.random.random(size=(4, 4)).round(2)
K = np.random.randint(-100, 100)

In [12]:
A

array([[0.35, 0.34, 0.94, 0.17],
       [0.2 , 0.09, 0.3 , 0.29],
       [0.96, 0.34, 0.02, 0.01],
       [0.19, 0.27, 0.92, 0.1 ]])

In [13]:
K

15

In [14]:
A*K

array([[ 5.25,  5.1 , 14.1 ,  2.55],
       [ 3.  ,  1.35,  4.5 ,  4.35],
       [14.4 ,  5.1 ,  0.3 ,  0.15],
       [ 2.85,  4.05, 13.8 ,  1.5 ]])

**Задача 2** \
Сформировать таблицу Пифагора.

In [15]:
n = 10 # 10 на 10
rows = np.arange(1, n+1).reshape(n, 1)
cols = np.arange(1, n+1) 
table = rows * cols

In [18]:
table

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

**Задача 3**\
Модифицировать программу6_3 таким образом, чтобы значения X, F1
и F2 были представлены двумерным массивом, состоящим из трех строк.